### ISSUE TITLE
Is there are missing districts?

### ISSUE THREAD

**Issue by yasseribrahim** [homaily/Saudi-Arabia-Regions-Cities-and-Districts#11]
SA, @homaily, Great Work my friend, 
I need help please, why 114 city have districts, and 3308 city does not have districts, also:
IS there a way to find missing districts or get boundaries of cities?

**Comment by homaily** [comment]
Hi @yasseribrahim,
Cities file includes cities and villages hence the missing districts in most of the entities there.

This repo is collected From public data, If you need more specific data feel free to checkout Saudi post api or google maps api which can help you with reverse lookup functionality.
