### ISSUE TITLE
i have issue with upload table Districts 

### ISSUE THREAD

**Issue by Mohamed1Gohar** [homaily/Saudi-Arabia-Regions-Cities-and-Districts#17]
#3037 - Invalid GIS data provided to function st_geomfromtext.

**Comment by imdhemy** [comment]
I investigated the issue. Here you can find the rows that contain invalid data: 

https://gist.github.com/imdhemy/09f79ec5d9700b2ac3c187d86dadac2e#file-invalid_rows-json

| Q | A |
| --- | --- | 
| Table | districts |
| Total | 3732 |
| Valid | 3710 |
| Invalid | 22 |
| MySQL version | 8.0 |


- NOTE [1]: I ignored Arabic names during the investigation.
- NOTE [2]: The investigation script is not supposed to be used in production.
