### ISSUE TITLE
 هل من الطبيعي تكرار نفس الإسم لأكثر من مدينة في المنطقة ؟

### ISSUE THREAD

**Issue by aramoudi** [homaily/Saudi-Arabia-Regions-Cities-and-Districts#5]
السلام عليكم

لا أعلم إذا هذا bug او انه هذا هو الطبيعي ؟

مثلاً في منطقة الرياض يوجد مدن بكثرة متكررة
* الرويضة
* الفيصلية
* القاعية
* الفيضة
* المشاش
* مشرفة 
* الخالدية
* الحفنة
* العقلة
* سعدة
* و غيرها...

الموضوع يتكرر ايضاً مع المناطق الاخرى

أم انها احياء و اعتبرت كمدن ؟

**Comment by homaily** [comment]
وعليكم السلام، طبيعي القرى والأحياء تكون بنفس الأسم في أماكن مختلفة
