### ISSUE TITLE
Cooridnates in JSON files not supported

### ISSUE THREAD

**Issue by ASAQR** [homaily/Saudi-Arabia-Regions-Cities-and-Districts#9]
Hi Homaily

I tried to use your json files and upload them but the coordinates stored as LATLONG format while it expected them to be LONGLAT format. I appreciate if you can share with me the files with the GEOJSON format or at least provide me the scripts on Oracle format. 

Thanks on advance

**Comment by homaily** [comment]
Hi @ASAQR 
Geojson format not available at the moment. You can use one of the available formats (json or sql) and transform it as you wish. This is an open source repo, any back contribution are welcome.
